config/routes.rb
Rails.application.routes.draw do
  root to: 'diaries#index'
  # 追加
  resources :diaries do
    post 'confirm', on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord
  # タイトルが空の場合は、バリデーションを発生させる
  validates :title, presence: true
  # モデルの中で、オブジェクトの住所がどこにあるかを geocoder に伝える
  geocoded_by :address
  # addressカラムに入った情報を元に『latitude』『longitude』に緯度・経度の情報が入る
  after_validation :geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :set_diary, only: %i[show edit update destroy]
  before_action :assignment_to_diary_instance_and_gon_lat_lng, only: %i[confirm create]

  def index
  end

  def show
  end

  def new
    @diary = Diary.new
  end

  def edit
    # 『@diary.addressに値が存在する場合』は...
    return unless @diary.address.present?

    # 『gon.lat_lng』に [@diary.latitude, @diary.longitude]を代入する
    gon.lat_lng = [@diary.latitude, @diary.longitude]
  end

  def confirm
    render :new if @diary.invalid?
  end

  def create
    return render :new if params[:back]

    if @diary.save
      redirect_to diaries_path
    else
      render :new
    end
  end

  def update
    if @diary.update(diary_params)
      redirect_to diaries_path
    else
      render :edit
    end
  end

  private

  def set_diary
    @diary = Diary.find(params[:id])
  end

  def diary_params
    params.require(:diary).permit(:title, :content, :address)
  end

  def assignment_to_diary_instance_and_gon_lat_lng
    @diary = Diary.new(diary_params)
    # 『gon.lat_lng』に緯度・経度を代入
    # 仮に『@diary.address = '東京タワー'』だった場合
    # 『gon.lat_lng = [35.6585805, 139.7454329]』と代入される
    # 『@diary.address = ''』だった場合は『nil』が代入される
    gon.lat_lng = Geocoder.coordinates(@diary.address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
  def choose_new_or_edit
    case action_name
    # 【確認画面から『戻る』】→ もう一度【確認画面】
    # 【日記新規投稿】 → 【バリデーション発生】 → もう一度【確認画面】
    # 以上の2点にも対応ができるように『'create'』『'confirm'』の両方を記述している
    when 'new', 'create', 'confirm'
      confirm_diaries_path
    when 'edit'
      diary_path
    end
  end
end

app/views/diaries/_form.html.erb
<%= form_with(model: @diary, local: true, url: choose_new_or_edit) do |form| %>
  <% if @diary.errors.any? %>
    <div>
      <%= @diary.errors.count %>のエラーが発生<br>
      <% @diary.errors.full_messages.each do |msg| %>
        <%= msg %><br>
      <% end %>
    </div>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <%# script内の『hidden_address.setAttribute("value", inputAddress)』を
  介して、【住所入力用のテキストボックス】の値を受け取る %>
  <%= form.hidden_field :address, id: "hidden_address" %>

  <div>
    イベント先
    <%# 住所入力用のテキストボックスを作成 %>
    <input id="address" type="textbox" value="">
    <%# 地図検索ボタンを作成 %>
    <input type="button" value="地図検索" onclick="codeAddress()">
  </div>

  <%# 地図検索ボタンを押すと、ここに【経度・緯度】が表示される %>
  <div id="display"></div>

  <%# 地図が表示される %>
  <div id='map' style='height: 600px; width: 600px;' ></div>

  <script>
    const display = document.getElementById('display')
    let map
    let marker

    // 地図の初期設定
    function initMap() {
      // 地図の作成
      map = new google.maps.Map(document.getElementById('map'), {
        center: {
          lat: 35.65858645,
          lng: 139.74544005796224
        },
        zoom: 9,
      });

      // 緯度・経度が存在する場合はif文の中身を実行
      // 緯度・経度が存在する状況は【日記新規作成確認画面から『戻る』場合】と【『日記編集』をする場合】がある
      // gonを使用してcontrollerから緯度・経度を取得
      if (!!gon.lat_lng) {
        const lat_lng = {lat: gon.lat_lng[0], lng: gon.lat_lng[1]};
         // 指定された座標でマップを中央に表示
        map.setCenter(lat_lng);
        // 指定された座標でマーカーを立てる
        marker = new google.maps.Marker({
          map: map,
          position: lat_lng
        });
      }
    }
    
    // 地図検索ボタンを押すと実行される関数
    function codeAddress() {
      // 【住所入力用のテキストボックス】の値を取得
      const inputAddress = document.getElementById('address').value;

      const geocoder = new google.maps.Geocoder()
      geocoder.geocode({
        'address': inputAddress
      // resultsに『ジオコーディングの結果』、statusに『ステータスコード』を渡す
      }, function (results, status) {
        // statusが『OK』の場合は...
        if (status == 'OK') {
          // 指定された座標でマップを中央に表示
          map.setCenter(results[0].geometry.location); 
          // 『既にmarkerに値がある』場合は...
          if (typeof marker != 'undefined') {
            // markerをnullにする（前のマーカーが削除される）
            marker.setMap(null);
          }
          // 指定された座標でマーカーを立てる
          marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
        });
        // 『hidden_address』に【住所入力用のテキストボックス】の値を送る
        const hidden_address = document.getElementById('hidden_address');
        hidden_address.setAttribute("value", inputAddress);

        // 検索結果が存在する場合は『display』に緯度・経度を表示させる
        display.textContent = "<%= '検索結果' %>" + results[0].geometry.location
        } else {
          // 検索結果が無い場合はその旨を表示させる 
          alert("<%= '検索結果がありません' %>" + status);
        }
      });
    }
  </script>

  <%# APIキーの読み込み %>
  <%# callback=initMap … APIが読み込まれたらinitMap()という関数を実行 %>
  <%# async … async属性は、外部のスクリプト・ファイルのスクリプトが使用可能になったら実行する属性 %>
  <%# defer … defer属性は、ページ読み込み時に、外部のスクリプト・ファイルのスクリプトを実行する属性 %>
  <%# 『async属性』と『defer属性』を両方指定した場合、 『async属性』に対応しているブラウザは『async属性』に従う。
  『async属性』に対応していないブラウザは『defer属性』に従う %>
  <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_KEY'] %>&callback=initMap" async defer></script>

  <%= form.submit %>
<% end %>

app/views/diaries/confirm.html.erb
<h2>日記新規投稿確認画面</h2>

<%= form_with(model: @diary, local: true) do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title, disabled: true %>
  </div>

  <div>
    <%= form.label :content %>
    <%= form.text_area :content, disabled: true %>
  </div>

  <div>
    <%= form.label :address %>
    <%= form.text_field :address, disabled: true %>
  </div>

  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :address %>

  <%# @diary.addressが存在する場合のみ地図が表示される %>
  <% if @diary.address.present? %>
    <div id='map' style='height: 600px; width: 600px;' ></div>

    <script>
      const lat_lng = {lat: gon.lat_lng[0], lng: gon.lat_lng[1]};
      function initMap() {
        const map = new google.maps.Map(document.getElementById('map'), {
          center: lat_lng,
          zoom: 9,
        });
        var marker = new google.maps.Marker({
          position: lat_lng,
          map: map
        });
      }
    </script>

    <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_KEY'] %>&callback=initMap" async defer></script>
  <% end %>

  <%= form.submit %>
  <%= form.submit '戻る', name: 'back' %>
<% end %>

app/views/diaries/edit.html.erb
<h2>日記編集</h2>

<%= render 'form' %>

<p>Find me in app/views/diaries/edit.html.erb</p>

app/views/diaries/index.html.erb
<h2>日記一覧</h2>

<%# 省略 %>

<%# 【data: {turbolinks: false}】の記述によりAPIの再読み込むを防ぐ %>
<%# 記述が無いと【JavaScript】のエラーが発生する↓ %>
<%# 【エラー内容】<%# You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors. %>
<%= link_to '日記新規投稿へ', new_diary_path, data: {turbolinks: false} %>

app/views/diaries/new.html.erb
<h2>日記新規投稿</h2>

<%= render 'form' %>

<%= link_to '日記一覧へ', diaries_path %>

app/views/diaries/show.html.erb
<h2>日記詳細</h2>
<p>Find me in app/views/diaries/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoogleMaps</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%# 「include_gon(init: true)」を追加 %>
    <%# 【(init: true)】を記述する事により、『リクエストごとにwindow.gon = {};を初期化』 %>
    <%# 記述が無いと『日記新規投稿画面』で【JavaScript】のエラーが発生する↓ %>
    <%# 【エラー内容】Uncaught (in promise) ReferenceError: gon is not defined %>
    <%= include_gon %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>